function PLOT_RAV2_GAWS_val_ts(data, img_dir,filename,site_name,t)
%%
close all
figure('Position', [50, -1000, 900, 1450]), hold on
sgtitle(site_name)

hAx(1) = subplot(5,1,1), hold on

Exist_Column = strcmp('t_2',data.Properties.VariableNames); val = Exist_Column(Exist_Column==1); 

if isempty(val) == 0
    plot(data.Time,data.t_T1,'r')
    plot(data.Time,data.t_2,'k')
    
    grid on
    ylabel('t')
    xlim(hAx(1) ,[t(1) t(end)])
    
    set(gca,'TickDir','out');
    set(gca, ...
      'Box'         , 'off'     , ...
      'TickDir'     , 'out'     , ...
      'TickLength'  , [.02 .02] , ...
      'XMinorTick'  , 'on'      , ...
      'YMinorTick'  , 'on'      , ...
      'YGrid'       , 'on'      , ...
      'XColor'      , [.3 .3 .3], ...
      'YColor'      , [.3 .3 .3], ...
      'LineWidth'   , 1         );
else 
end
  
hAx(2) = subplot(5,1,2), hold on
  
  Exist_Column = strcmp('f_2',data.Properties.VariableNames); val = Exist_Column(Exist_Column==1); 

if isempty(val) == 0
    
    plot(data.Time,data.f_T1,'r')
    plot(data.Time,data.f_2,'k')
    grid on
    ylabel('f')
    xlim(hAx(2) ,[t(1) t(end)])    
    
    set(gca,'TickDir','out');
    set(gca, ...
      'Box'         , 'off'     , ...
      'TickDir'     , 'out'     , ...
      'TickLength'  , [.02 .02] , ...
      'XMinorTick'  , 'on'      , ...
      'YMinorTick'  , 'on'      , ...
      'YGrid'       , 'on'      , ...
      'XColor'      , [.3 .3 .3], ...
      'YColor'      , [.3 .3 .3], ...
      'LineWidth'   , 1         );
    

else
end
  
hAx(3) = subplot(5,1,3), hold on

  Exist_Column = strcmp('sw_in_2',data.Properties.VariableNames); val = Exist_Column(Exist_Column==1); 

if isempty(val) == 0
    
    plot(data.Time,data.sw_in_T1,'r')
    plot(data.Time,data.sw_in_2,'k')
    grid on
    ylabel('sw_i')
    xlim(hAx(3),[t(1) t(end)])    
    
    set(gca,'TickDir','out');
    set(gca, ...
      'Box'         , 'off'     , ...
      'TickDir'     , 'out'     , ...
      'TickLength'  , [.02 .02] , ...
      'XMinorTick'  , 'on'      , ...
      'YMinorTick'  , 'on'      , ...
      'YGrid'       , 'on'      , ...
      'XColor'      , [.3 .3 .3], ...
      'YColor'      , [.3 .3 .3], ...
      'LineWidth'   , 1         );
else
end
  
hAx(4) = subplot(5,1,4), hold on

  Exist_Column = strcmp('lw_in_2',data.Properties.VariableNames); val = Exist_Column(Exist_Column==1); 

if isempty(val) == 0
    
    plot(data.Time,data.lw_in_T1,'r')
    plot(data.Time,data.lw_in_2,'k')
    grid on
    ylabel('lw_i')
    xlim(hAx(4),[t(1) t(end)])    
    
    set(gca,'TickDir','out');
    set(gca, ...
      'Box'         , 'off'     , ...
      'TickDir'     , 'out'     , ...
      'TickLength'  , [.02 .02] , ...
      'XMinorTick'  , 'on'      , ...
      'YMinorTick'  , 'on'      , ...
      'YGrid'       , 'on'      , ...
      'XColor'      , [.3 .3 .3], ...
      'YColor'      , [.3 .3 .3], ...
      'LineWidth'   , 1         );
else
end
  
hAx(5) = subplot(5,1,5), hold on
  Exist_Column = strcmp('rh_2',data.Properties.VariableNames); val = Exist_Column(Exist_Column==1); 

if isempty(val) == 0
    
    plot(data.Time,data.rh_T1,'r')
    plot(data.Time,data.rh_2,'k')
    grid on
    ylabel('rh')
    xlim(hAx(5),[t(1) t(end)])    
    
    set(gca,'TickDir','out');
    set(gca, ...
      'Box'         , 'off'     , ...
      'TickDir'     , 'out'     , ...
      'TickLength'  , [.02 .02] , ...
      'XMinorTick'  , 'on'      , ...
      'YMinorTick'  , 'on'      , ...
      'YGrid'       , 'on'      , ...
      'XColor'      , [.3 .3 .3], ...
      'YColor'      , [.3 .3 .3], ...
      'LineWidth'   , 1         );
else
end
    

legend('RAV2','GAWS')
set(gcf, 'Color', 'w');
cd(img_dir)
  export_fig(filename, '-png'); 